# Generated by Django 6.0 on 2026-02-06 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryaddress',
            options={},
        ),
        migrations.AlterField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
        migrations.AlterField(
            model_name='deliverymarketlog',
            name='market',
            field=models.CharField(max_length=100),
        ),
    ]
