# Generated by Django 6.0.1 on 2026-02-04 17:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fargo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('fargo_status', models.CharField(choices=[('created', 'Buyurtma yaratildi'), ('confirming', 'Buyurtma tasdiqlanish jarayonida'), ('preparing', 'Kuryer buyurtmani tayyorlamoqda'), ('sent_to_fargo', 'Buyurtma fargo punktga topshirildi'), ('delivered', 'Buyurtma mijozga topshirildi'), ('returned', 'Buyurtma qaytarildi'), ('at_fargo', 'Buyurtma fargo punktida'), ('to_region', 'Viloyatga yuborilmoqda'), ('region_received', 'Viloyat punktga topshirildi'), ('to_client', 'Mijozga yuborilmoqda'), ('failed_call', 'Kuryer mijoz bilan boglana olmadi')], default='created', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=255)),
                ('delivery', models.CharField(max_length=255)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('created', 'Buyurtma yaratildi'), ('confirming', 'Buyurtma tasdiqlanish jarayonida'), ('preparing', 'Kuryer buyurtmani tayyorlamoqda'), ('sent_to_fargo', 'Buyurtma fargo punktga topshirildi'), ('delivered', 'Buyurtma mijozga topshirildi'), ('returned', 'Buyurtma qaytarildi'), ('at_fargo', 'Buyurtma fargo punktida'), ('to_region', 'Viloyatga yuborilmoqda'), ('region_received', 'Viloyat punktga topshirildi'), ('to_client', 'Mijozga yuborilmoqda'), ('failed_call', 'Kuryer mijoz bilan boglana olmadi')], default='created', max_length=30)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('cash_card', 'Cash / Card'), ('merchant', 'Merchant')], max_length=20)),
                ('is_send_fargo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.fargo')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('in_tashkent', models.BooleanField(default=True)),
                ('address_name', models.CharField(max_length=255)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('street', models.CharField(max_length=255)),
                ('home', models.CharField(max_length=20)),
                ('apartment', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.order')),
            ],
        ),
    ]
